/**
 * Centralized configuration — all env vars and derived constants in one place.
 */
import { join } from "node:path";

// --- Paths ---
export const STATE_DIR = join(process.env.HOME ?? "~", ".edith");
export const DB_FILE = join(STATE_DIR, "edith.db");
export const SCHEDULE_FILE = join(STATE_DIR, "schedule.json");
export const LOCATIONS_FILE = join(STATE_DIR, "locations.json");
export const REMINDERS_FILE = join(STATE_DIR, "reminders.json");
export const EVENTS_FILE = join(STATE_DIR, "events.jsonl");
export const TASKBOARD_FILE = join(STATE_DIR, "taskboard.md");
export const TASKBOARD_ARCHIVE_DIR = join(STATE_DIR, "taskboard-archive");
export const SESSION_FILE = join(STATE_DIR, "session-id");
export const PID_FILE = join(STATE_DIR, "edith.pid");
export const DEAD_LETTER_FILE = join(STATE_DIR, "dead-letters.json");
export const INBOX_DIR = join(STATE_DIR, "inbox");

// --- Telegram ---
export const TELEGRAM_BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN ?? "";
export const CHAT_ID = Number(process.env.TELEGRAM_CHAT_ID ?? "0");
export const TELEGRAM_USER_ID = process.env.TELEGRAM_USER_ID ?? "";
export const SMS_BOT_ID = process.env.TELEGRAM_SMS_BOT_ID ?? "";

// --- Twilio ---
export const TWILIO_SID = process.env.TWILIO_ACCOUNT_SID ?? "";
export const TWILIO_TOKEN = process.env.TWILIO_AUTH_TOKEN ?? "";
export const TWILIO_WA_FROM = process.env.TWILIO_WHATSAPP_FROM ?? "";
export const TWILIO_SMS_FROM = process.env.TWILIO_SMS_FROM ?? "";

// --- n8n ---
export const N8N_URL = process.env.N8N_URL ?? "http://localhost:5679";

// --- Google ---
export const GOOGLE_API_KEY = process.env.GOOGLE_GENERATIVE_AI_API_KEY ?? "";
// Gmail OAuth — used by lib/google-auth.ts and lib/gmail.ts
export const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID ?? "";
export const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET ?? "";
export const GOOGLE_REFRESH_TOKEN = process.env.GOOGLE_REFRESH_TOKEN ?? "";
export const GOOGLE_ACCESS_TOKEN = process.env.GOOGLE_ACCESS_TOKEN ?? "";

// --- OpenRouter ---
export const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY ?? "";

// --- Misc ---
export const GROQ_API_KEY = process.env.GROQ_API_KEY ?? "";
export const INBOX_MAX_AGE_MS = 7 * 24 * 60 * 60 * 1000;
export const BACKOFF_SCHEDULE = [5_000, 15_000, 30_000, 60_000, 120_000, 300_000];

// --- Reflector ---
export const REFLECTOR_ENABLED = process.env.REFLECTOR_ENABLED !== "false"; // on by default
export const REFLECTOR_TOOL_CALL_FREQUENCY = Number(process.env.REFLECTOR_FREQUENCY ?? "4");
export const REFLECTOR_EVAL_ONLY_RATIO = Number(process.env.REFLECTOR_EVAL_ONLY_RATIO ?? "0.3"); // 30% sessions get eval-only (no injections)

// --- Dispatch / circuit breaker ---
export const MAX_CONSECUTIVE_FAILURES = 5;
export const CIRCUIT_BREAKER_COOLDOWN_MS = 10 * 60 * 1000; // 10 minutes
export const QUERY_TIMEOUT_MS = 5 * 60 * 1000; // 5 minutes max per dispatch
export const LIGHTWEIGHT_TIMEOUT_MS = 90 * 1000; // 90 seconds for lightweight tasks
export const INTER_DISPATCH_DELAY_MS = 3_000;

// --- Proactive limits ---
export const PROACTIVE_MAX_PER_HOUR = 2;
export const PROACTIVE_COOLDOWN_MINUTES = 60;
export const PROACTIVE_QUIET_START = 22;
export const PROACTIVE_QUIET_END = 8;

// --- Cost governance ---
export const DAILY_COST_LIMIT_USD = Number(process.env.DAILY_COST_LIMIT_USD ?? "100");

// --- Device Auth (CLOUD-AUTH-048) ---
/** Shared secret used to sign/verify device JWTs. Generated by setup.sh. */
export const DEVICE_SECRET = process.env.DEVICE_SECRET ?? "";

// --- State / polling ---
export const POLL_INTERVAL_MS = 3_000;
export const SCHEDULE_CHECK_MS = 60_000;
export const EVENTS_MAX_AGE_MS = 48 * 60 * 60 * 1000;
