/**
 * Centralized configuration — all env vars and derived constants in one place.
 */
import { join } from "node:path";

// --- Cloud mode detection ---
export const IS_CLOUD =
	!!process.env.RAILWAY_ENVIRONMENT ||
	process.env.CLOUD_MODE === "true" ||
	process.env.CLOUD_MODE === "1";

// --- Paths ---
// State lives inside the project so the AI agent can see it when debugging.
// Cloud mode: uses /data/.state (Railway volume) or falls back to project dir.
const PROJECT_DIR = join(import.meta.dir, "..");
export const STATE_DIR = process.env.EDITH_STATE_DIR ?? join(PROJECT_DIR, ".state");
export const DB_FILE = join(STATE_DIR, "edith.db");
export const EVENTS_FILE = join(STATE_DIR, "events.jsonl");
export const TASKBOARD_FILE = join(STATE_DIR, "taskboard.md");
export const TASKBOARD_ARCHIVE_DIR = join(STATE_DIR, "taskboard-archive");
export const DOWNLOADS_DIR = join(STATE_DIR, "downloads");

// --- Telegram ---
export const TELEGRAM_BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN ?? "";
export const CHAT_ID = Number(process.env.TELEGRAM_CHAT_ID ?? "0");
export const TELEGRAM_USER_ID = process.env.TELEGRAM_USER_ID ?? "";
export const SMS_BOT_ID = process.env.TELEGRAM_SMS_BOT_ID ?? "";

// --- Twilio ---
export const TWILIO_SID = process.env.TWILIO_ACCOUNT_SID ?? "";
export const TWILIO_TOKEN = process.env.TWILIO_AUTH_TOKEN ?? "";
export const TWILIO_WA_FROM = process.env.TWILIO_WHATSAPP_FROM ?? "";
export const TWILIO_SMS_FROM = process.env.TWILIO_SMS_FROM ?? "";

// --- Google ---
export const GOOGLE_API_KEY = process.env.GOOGLE_GENERATIVE_AI_API_KEY ?? "";
// Gmail OAuth — used by lib/google-auth.ts and lib/gmail.ts
export const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID ?? "";
export const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET ?? "";
export const GOOGLE_REFRESH_TOKEN = process.env.GOOGLE_REFRESH_TOKEN ?? "";
export const GOOGLE_REFRESH_TOKEN_2 = process.env.GOOGLE_REFRESH_TOKEN_2 ?? "";

/** Google account identifiers — provider keys used in oauth_tokens table */
export const GOOGLE_ACCOUNTS = [
	{ provider: "google", label: "phoenixrr2113@gmail.com", refreshTokenEnv: "GOOGLE_REFRESH_TOKEN" },
	{
		provider: "google-2",
		label: "randyrowanwilson@gmail.com",
		refreshTokenEnv: "GOOGLE_REFRESH_TOKEN_2",
	},
] as const;
export const GOOGLE_ACCESS_TOKEN = process.env.GOOGLE_ACCESS_TOKEN ?? "";

// --- OpenRouter ---
export const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY ?? "";

// --- ntfy.sh push notifications ---
export const NTFY_SERVER = process.env.NTFY_SERVER ?? "https://ntfy.sh";
export const NTFY_TOPIC = process.env.NTFY_TOPIC ?? "";

// --- Misc ---
export const GROQ_API_KEY = process.env.GROQ_API_KEY ?? "";
export const DOWNLOADS_MAX_AGE_MS = 24 * 60 * 60 * 1000; // 24h
export const BACKOFF_SCHEDULE = [5_000, 15_000, 30_000, 60_000, 120_000, 300_000];

// --- Reflector ---
// Disabled in cloud — spawns a second Claude subprocess that OOMs on Railway
export const REFLECTOR_ENABLED = IS_CLOUD ? false : process.env.REFLECTOR_ENABLED !== "false";
export const REFLECTOR_TOOL_CALL_FREQUENCY = Number(process.env.REFLECTOR_FREQUENCY ?? "4");
export const REFLECTOR_EVAL_ONLY_RATIO = Number(process.env.REFLECTOR_EVAL_ONLY_RATIO ?? "0.3"); // 30% sessions get eval-only (no injections)

// --- Sentinel (post-message quality evaluation) ---
// Disabled in cloud — spawns a Claude subprocess that OOMs on Railway (same as reflector)
export const SENTINEL_ENABLED = IS_CLOUD ? false : process.env.SENTINEL_ENABLED !== "false";

// --- Dispatch / circuit breaker ---
export const MAX_CONSECUTIVE_FAILURES = 5;
export const CIRCUIT_BREAKER_COOLDOWN_MS = 10 * 60 * 1000; // 10 minutes
export const QUERY_TIMEOUT_MS = IS_CLOUD ? 8 * 60 * 1000 : 5 * 60 * 1000; // cloud: 8min, local: 5min
export const LIGHTWEIGHT_TIMEOUT_MS = IS_CLOUD ? 3 * 60 * 1000 : 90 * 1000; // cloud: 3min, local: 90s
export const INTER_DISPATCH_DELAY_MS = 3_000;

// --- Proactive limits ---
export const PROACTIVE_MAX_PER_HOUR = 2;
export const PROACTIVE_COOLDOWN_MINUTES = 60;
export const PROACTIVE_QUIET_START = 22;
export const PROACTIVE_QUIET_END = 8;

// --- Device Auth (CLOUD-AUTH-048) ---
/** Shared secret used to sign/verify device JWTs. Generated by setup.sh. */
export const DEVICE_SECRET = process.env.DEVICE_SECRET ?? "";

// --- Scheduler coordination ---
/** Instance identifier — used in scheduler_claims to track who fired what. */
export const INSTANCE_ID = IS_CLOUD ? "cloud" : "local";

// --- State / polling ---
export const POLL_INTERVAL_MS = 3_000;
export const SCHEDULE_CHECK_MS = 60_000;
export const EVENTS_MAX_AGE_MS = 48 * 60 * 60 * 1000;
